version: '3'

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    command: mongod --port 27030
    container_name: noodlapp-mongodb
    ports:
      - "27030:27030"
    volumes:
      - mongodb-data:/data/noodlapp-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meinname
      MONGO_INITDB_ROOT_PASSWORD: meinpasswort
      MONGO_INITDB_DATABASE: noodlapp

  cloudservice:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noodlapp
    environment:
      NODE_ENV: production
      PORT: 3700
      MASTER_KEY: meinmasterkey
      APP_ID: noodlapp
      DATABASE_URI: mongodb://meinname:meinpasswort@mongodb:27030/noodlapp?authSource=admin
      PUBLIC_SERVER_URL: http://mediacomvalentin.de:3700
    ports:
      - "3700:3700"
    links:
      - mongodb

volumes:
  mongodb-data:
